### PR TITLE
🐛 Fix parentheses not being kept in AST

### LINKED ISSUE #34: 🐛 Incorrect output of conditionals in parentheses
Using parenthesised conditions, the parentheses are not emitted in the output, resulting in incorrect operation order.

e.g. `3 + (if 2 < 3 then 4 else 2) - 1` should be output as `3 + (2 < 3 ? 4 : 2) - 1` which would evaluate to 6, but is actually emitted as `3 + 2 < 3 ? 4 : 2 - 1` which evaluates to 4 (js evaluates it as `(3 + 2) < 3 ? 4 : (2 - 1)`).

### PR DESCRIPTION
**Pull request by Alpvax**
Add SubExpression, optimise to strip parentheses around a single term.

Fixes #34

### CODE REVIEW

**Review by pd-andy — APPROVED** [review]
Yeah great stuff, an explicit `SubExpression` type solves a lot of problems and I like that we're optimising it away where possible.

I'm going to push some small code style changes and a couple of tests and then get this merged, thanks.

File: src/Ren/Compiler/Optimise/Expression.elm [hunk 1]
```diff
@@ -25,21 +22,22 @@ optimise =
     Transform.transformAll recursiveTransformation
         (Transform.orList
             [ constantFold
-            , parenStrip
+            , stripParentheses
```
Comment (Alpvax) [inline src/Ren/Compiler/Optimise/Expression.elm:25]: Why is this verb-noun, but the original noun-verb?
